---
title: Research
summary: Displaying my published and unblished papers
date: "2018-06-28T00:00:00Z"

reading_time: false  # Show estimated reading time?
share: false  # Show social sharing links?
profile: false  # Show author profile?
comments: false  # Show comments?

# Optional header image (relative to `static/img/` folder).
header:
  caption: ""
  image: ""
---

<style>
div.gray { background-color:#F3F3F3; border-radius: 5px; padding: 20px;}
</style>

### Working Papers

---

<div class = "gray">
[**Nowcasting US GDP Using Tree-Based Ensemble Models and Dynamic Factors**](../files/WP1.pdf) \
(with Ege Yazgan)

<span style="color: red;">Abstract:</span>

In this study, we nowcast quarter over quarter US GDP growth rates between 2000Q2 and 2018Q4 using tree-based ensemble machine learning models namely bagged decision trees, random forests and stochastic gradient tree boosting. To solve the ragged problem in nowcasting and improve the prediction performance of machine learning models, we adopt a dynamic factor model. Dynamic factors extracted from 10 groups of financial and macroeconomic variables are fed to machine learning models for nowcasting US GDP. Our results show that tree-based ensemble models usually outperform linear dynamic factor models. We also point out that factors obtained from real variables are more influential for machine learning models but the impact of factors derived from financial and price variables increase after the sub-prime mortgage crisis.
</div>

<br>

<div class = "gray">
[**Time Varying Taylor Rule Estimation For Turkey with Flexible Least Square Method**](../files/WP2.pdf) \
(with Burak Alparslan Eroglu)

<span style="color: red;">Abstract:</span>

In this study, we estimate a time-varying Taylor rule for evaluating the policy reaction function of the Central Bank of the Republic of Turkey. Even though the Turkish economy has constantly been evolving in the last 15 years, previous studies that analyze the monetary policy rule of the CBRT mainly use time-invariant monetary policy functions. We propose a flexible two-stage least square regression to deal with both instability and endogeneity problems in monetary policy functions. By analyzing the period between 2004 and 2019, we clearly show that the monetary policy function of the Central Bank of the Republic of Turkey changes over time and using a time-invariant monetary policy rule model would yield incorrect results.
</div>

### Published Papers

---

<div class = "gray">
[**Identifying US Business Cycle Regimes using Dynamic Factors and Neural Network Models**](https://onlinelibrary.wiley.com/doi/abs/10.1002/for.2658) &middot;
Journal of Forecasting, 2020

<span style="color: red;">Abstract:</span>

We use dynamic factors and neural network models to identify current and past states (instead of future) of the US business cycle. In the first step, we reduce noise in data by using a moving average filter. Dynamic factors are then extracted from a large‐scale data set consisted of more than 100 variables. In the last step, these dynamic factors are fed into the neural network model for predicting business cycle regimes. We show that our proposed method follows US business cycle regimes quite accurately in‐sample and out‐of‐sample without taking account of the historical data availability. Our results also indicate that noise reduction is an important step for business cycle prediction. Furthermore, using pseudo real time and vintage data, we show that our neural network model identifies turning points quite accurately and very quickly in real time.
</div>

<br>

<div class = "gray">
[**Determinants of Turkish female Labour Force Participation an Analysis with Manufacturing Firm Level Data**](https://www.tandfonline.com/doi/abs/10.1080/13504851.2019.1707757?journalCode=rael20) &middot;
Applied Economics Letters, 2020\
(with Nazlı Karamollaoğlu)

<span style="color: red;">Abstract:</span>

Compared to other developing countries, Turkey has a very low female labour participation rate. Previous studies usually focus on the labour supply side of female employment. Unlike the previous literature, this paper investigates firm-level determinants of female employment in manufacturing firms using a unique micro data set constructed using different sources. After controlling for geographical variation, firm, and industry-specific factors, our results show that larger firms, exporter firms, firms with higher part-time worker ratio, and foreign-owned firms have higher female employment rate whereas younger firms, firms with higher labour productivity, and firms with long working hours have lower female employment rate.
</div>

<br>

<div class = "gray">
[**Identifying Turkish Business Cycle Regimes in Real Time**](https://www.tandfonline.com/doi/pdf/10.1080/13504851.2019.1607243?needAccess=true) &middot;
Applied Economics Letters, 2019

<span style="color: red;">Abstract:</span>

In this study, we analyse the real-time identification performance of the BBQ method and the Markov switching (MS) model in the case of Turkey by comparing their real-time and ex-post identification results between 1997M01-2017M12. We show that both the BBQ and the MS methodologies identify the nearly same turning point dates for the Turkish economy both ex-post and in real time by using a pseudo real-time data set. We also calculate the real-time identification lag of models and show that the MS model and the BBQ method identify a turning point with a 3–4 months lag and a 6 months lag, respectively. Finally, we show that data revisions do not have a significant impact on the real-time identification performance of the models between 2005M01-2017M12.
</div>

<br>

<div class = "gray">
[**Evaluating the Effect of Geopolitical Risks on the Growth Rates of Emerging Countries**](http://www.accessecon.com/Pubs/EB/2019/Volume39/EB-19-V39-I1-P71.pdf) &middot;
Economics Bulletin, 2019\
(with Huseyin Kaya and Dinçer Dedeoğlu)

<span style="color: red;">Abstract:</span>

In this study, we analyze the relationship between geopolitical risks and growth using annual panel data from 18 emerging countries for the period from 1986 to 2016. For a robustness check, we use panel data with 5-year intervals. The news-based indices of Caldara and Iacoviello (2018) were used as a proxy for geopolitical risks. Our results show that the effect of geopolitical risks on growth rates is negative and significant. A 10 point increase in the geopolitical risk index causes a 0.2–0.4% decline in the GDP growth rate.
</div>

<br>

<div class = "gray">
[**On the Performance of Wavelet Based Unit Root Tests**](http://www.mdpi.com/1911-8074/11/3/47) &middot;
Journal of Risk and Financial Management, 2018\
(with Burak Alparslan Eroğlu)

<span style="color: red;">Abstract:</span>

In this paper, we apply the wavelet methods in the popular Augmented Dickey-Fuller and M types of unit root tests. Moreover, we provide an extensive comparison of the wavelet based unit root tests which also includes the recent contributions in the literature. Moreover, we derive the asymptotic properties of the wavelet based unit root tests under generalized least squares detrending mechanism. We demonstrate that the wavelet based M tests exhibit better size performance even in problematic cases such as the presence of negative moving average innovations. However, the power performances of the wavelet based unit root tests are quite similar to each other.
</div>

<br>

<div class = "gray">
[**Evaluating Nowcasts of Bridge Equations with Advanced Combination Schemes for the Turkish Unemployment Rate**](https://www.sciencedirect.com/science/article/pii/S0264999317308623) &middot;
Economic Modelling, 2018\
(with Ege Yazgan)

<span style="color: red;">Abstract:</span>

The paper analyzes the point and density predictive performance of alternative nowcast combination schemes in the context of bridge equations for the Turkish unemployment rate. Furthermore, we also nowcast the unemployment rate by using dynamic factor models (DFMs). Our results indicate that most of the sophisticated forecast combination methods have better predictive accuracy than the simple forecast combinations, especially in higher forecast horizons, which constitutes a case for the nowcast combination puzzle. Furthermore, most of bridge equations with the advanced forecast combination schemes usually outperform DFMs which are assumed to be superior to the bridge equations. This latter result indicates that bridge equations augmented by advanced forecast combination schemes may be a viable alternative to the DFM. Finally, we show that real and labor variables play the most important role for nowcasting the Turkish unemployment rate, whereas financial variables and surveys do not seem to be beneficial. Overall, our results indicate that advanced combination schemes can increase the performance of nowcasting models.
</div>

<br>

<div class = "gray">
[**Nowcasting the New Turkish GDP**](http://www.accessecon.com/Pubs/EB/2018/Volume38/EB-18-V38-I2-P105.pdf) &middot;
Economics Bulletin, 2018\
(with Ege Yazgan)

<span style="color: red;">Abstract:</span>

In this study, we predict year-on-year and quarter-on-quarter Turkish GDP growth rates between 2012:Q1 and 2016:Q4 with a medium-scale dataset. Our proposed model outperforms both the competing dynamic factor model (DFM) and univariate benchmark models. Our results suggest that in nowcasting current GDP, all relevant information is released within the contemporaneous quarter; hence, no predictive power is added afterwards. Moreover, we show that the inclusion of construction/service sector variables and credit variables improves the prediction accuracy of the DFM.
</div>

<br>

<div class = "gray">
[**Nowcasting Turkish GDP and News Decomposition**](https://www.sciencedirect.com/science/article/pii/S0169207016300693) &middot;
International Journal of Forecasting, 2016\
(with Michele Modugno and Ege Yazgan)

<span style="color: red;">Abstract:</span>

Real gross domestic product (GDP) data in Turkey are released with a very long delay relative those of to other economies, between 10 and 13 weeks after the end of the reference quarter. This means that policy makers, the media, and market practitioners have to infer the current state of the economy by examining data that are more timely and are released at higher frequencies than the GDP. This paper proposes an econometric model that allows us to read through these more current and higher-frequency data automatically, and translate them into nowcasts for the Turkish real GDP. Our model outperforms the nowcasts produced by the Central Bank of Turkey, the International Monetary Fund, and the Organisation for Economic Co-operation and Development. Moreover, our model allows us to quantify the importance of each variable in our dataset for nowcasting Turkish real GDP. In line with the findings for other economies, we find that real variables play the most important role; however, contrary to the findings for other economies, we find that financial variables are as important as surveys.
</div>

<br>

### National Published Papers

---

<div class = "gray">
[**Estimating the Forward-Looking Taylor Rule for Turkey under Multiple Structural Breaks**](https://www.peterlang.com/view/9783631784396/html/ch10.xhtml?) &middot;
Current Issues in Turkish Economics, 2019\
(with Burak Alparslan Eroğlu and Haluk Yener)

<span style="color: red;">Abstract:</span>

We estimate a forward-looking Taylor rule for Turkey covering both implicit and explicit inflation-targeting periods. In this analysis, we also consider the presence of structural breaks in the policy coefficients. Even though the Turkish economy has been undergoing several structural changes since 2002, the previous studies that estimate the monetary policy rule for Turkey disregard structural breaks, while fitting a policy reaction function. In this study, we examine a Taylor rule for Turkey using a two-stage least square regression that is coupled with the analysis of multiple structural breaks with unknown dates. By using this methodology, we show that the monetary policy function of the Central Bank of the Republic of Turkey exhibits four different periods. This result demonstrates that it is crucial to take account of structural breaks, while estimating monetary policy rules.
</div>

<br>

<div class = "gray">
[**Evaluating the Asymmetric Effects of Production, Interest Rate and Exchange Rate on the Turkish Stock Prices**](https://dergipark.org.tr/download/article-file/703505) &middot;
Ege Academic Review, 2019\
(with Huseyin Kaya)

<span style="color: red;">Abstract:</span>

The relationship between stock prices and macro variables has been studied exhaustively in the literature. However, most of the studies assume that this relationship is linear. In this paper, we evaluate the asymmetric effects of production, the interest rate and the exchange rate on Turkish stock prices using non-linear autoregressive distributed lags models. We find that there are both long-run and short-run asymmetric relationships between macro variables and Turkish stock prices. Our results indicate that non-linear models can yield more plausible results compare to linear models. The relationship between stock prices and macro variables has been studied exhaustively in the literature. However, most of the studies assume that this relationship is linear. In this paper, we evaluate the asymmetric effects of production, the interest rate and the exchange rate on Turkish stock prices using non-linear autoregressive distributed lags models. We find that there are both long-run and short-run asymmetric relationships between macro variables and Turkish stock prices. Our results indicate that non-linear models can yield more plausible results compare to linear models.
</div>

<br>

<div class = "gray">
[**The Exchange Rate Pass-Through for Main Consumption Groups (in Turkish)**](http://www.ekonomikyorumlar.com.tr/files/articles/1568119468.pdf) &middot;
Finans Politik & Ekonomik Yorumlar, 2019\
(with Huseyin Kaya)

<span style="color: red;">Abstract:</span>

In this research, we estimate the exchange rate pass-through for main consumption groups of consumer price index. The change in exchange rates in Turkey is among the dominant factors affecting short-term inflation. Existing literature investigates the exchange rate pass-through to consumer price inflation. However, the effects of change in exchange rate on main expenditure groups of consumer price index may be different. In this research, we first analyze the exchange rate pass-through for each main consumption group. Then, we estimate exchange rate pass-through for various income groups using consumption expenditures. Results show that transportation, other goods and services, and food and non-alcoholic beverages groups have highest exchange rate pass-through effects. Furthermore, we find that households with highest income and lowest income brackets are affected from inflation induced by exchange rate at similar rates. 
</div>

<br>

<div class = "gray">
[**An Evaluation of Inflation Expectations in Turkey**](https://www.sciencedirect.com/science/article/pii/S1303070116300385) &middot;
Central Bank Review, 2017\
(with Ege Yazgan)

<span style="color: red;">Abstract:</span>

Expectations of inflation play a critical role in the process of price setting in the market. Central banks closely follow developments in inflation expectations to implement a successful monetary policy. The Central Bank of the Republic of Turkey (CBRT) conducts a survey of experts and decision makers in the financial and real sectors to reveal market expectations and predictions of current and future inflation. The survey is conducted every month. This paper examines the accuracy of these survey predictions using forecast evaluation techniques. We focus on both point and sign accuracy of the predictions. Although point predictions from CBRT surveys are compared with those of autoregressive models, sign predictions are evaluated on their value to a user. We also test the predictions for bias. Unlike the empirical evidence from other economies, our results show that autoregressive models outperform most of inflation expectations in forecasting inflation. This indicates that inflation expectations have poor point forecast accuracies. However, we show that sign predictions for all inflation expectations have value to a user.
</div>